### PR TITLE
Adding pure.js to the list?

### PR DESCRIPTION
**Pull request by pure**
Hi Garran,
I've added pure.js to the list of template engines, do you mind to add it?
Cheers,

### CODE REVIEW

**Comment by garann** [comment]
Sorry for letting this sit so long. If you remove the 'speedy' and 'parts' classes, I'll go ahead and merge it. Thanks!

**Comment by pure** [comment]
I'm quite late too!
pure.js allow partials and recursive templates, what made you doubt about it?

For speedy, well... it may be slower than some raw string ones.
The speed of a web app is more about network latency than rendering time.
Comparing tens of msec of rendering compared with hundreds of latency, doesn't make a big difference.

Cheers,

**Comment by garann** [comment]
Ah - I didn't see anything in the documentation about creating partial templates, but perhaps I missed it. Do you have a link? 'Speedy' isn't merely an adjective in this case - it corresponds to the question "is this one of the very fastest?" which just shows the fastest three.

**Comment by pure** [comment]
A compiled template is a JS function, that can be called inside another template logic.
Here is a particular case of a template with an inner call to itself:
http://beebole.com/pure/documentation/recursion-example

line 51 the template is compiled
line 52 the rendering starts
line 46 recurse, etc... Here it could be a call to another partial template.

Ok, for dropping speedy.
It looks my explanation on why raw speed does not matter client side needs some rework to impact.

**Comment by garann** [comment]
Thanks for the link. I didn't find that when I looked over the docs. 

The nice thing about speediness is that, as you point out, it may or may not be a crucial factor, so folks using this tool aren't obligated to consider it. :) If you drop that I'll merge this in.

**Comment by pure** [comment]
Most people come from a server rendering past where speed is a crucial factor. I was like that.
But ok. I removed it.
Thanks.

**Comment by garann** [comment]
Merged. Thanks!

**Pull request merged**
